### ISSUE TITLE
Error se cierra sin ejecutarse 

### ISSUE THREAD

**Issue by Axel3026** [SharkiCS/LoL-Summoner-Spells-2021#1]
Soy de LAS y se me cierra solo y no funciona, como puedo arreglarlo?

**Comment by SharkiCS** [comment]
¡Hola! ¿podrías decirme la serie de pasos que sigues hasta que se cierra? recuerda que es necesario que tu cliente esté abierto antes de ejecutar el programa, una vez lo abras con tu cliente previamente abierto deberia reconocer tu usuario abajo en verde. Si no puedes llegar a estos pasos uno de los posibles problemas podría ser dónde tienes tu league instalado, el programa lo busca en la particion C, dame más información de lo sucedido e intento arreglarlo! :)

**Comment by Axel3026** [comment]
Hola y gracias por responderme el nombre aparece todo bien, pero cuando le doy a Start y mi api esta puesta ahí, solo se cierra, me encantaria hacerte un GIF asi lo ves como lo hago.
![image](https://user-images.githubusercontent.com/87623383/145689796-7ddf195e-f1ca-498a-a11a-a754e5f302fc.png)

**Comment by Axel3026** [comment]
![Animation](https://user-images.githubusercontent.com/87623383/145690162-a37e0a33-f9cd-470a-8d0b-7774833de176.gif)
Ahora si, hago todo lo que usted dice, pero nada, yo pensaba que era un error del server LAS, y que solo funciona en otras regiones

**Comment by SharkiCS** [comment]
¡Hola de nuevo! Los pasos que sigues son los correctos, es posible que sea un problema con la región. ¿Podrias hacerme una captura de pantalla del siguiente comando en la consola de windows? 

```
wmic PROCESS WHERE name='LeagueClientUx.exe' GET commandline
``` 
(Necesitas tener League of Legends abierto)

**Comment by Axel3026** [comment]
"C:/Riot Games/League of Legends/LeagueClientUx.exe" "--riotclient-auth-token=JF0Lqso75EvK6LJpK1_TYw" "--riotclient-app-port=50537" "--no-rads" "--disable-self-update" "--region=LA2" "--locale=es_MX" "--remoting-auth-token=gzBL9wAwF3lCrq4vsa8wng" "--respawn-command=LeagueClient.exe" "--respawn-display-name=League of Legends" "--app-port=50604" "--install-directory=C:\Riot Games\League of Legends" "--app-name=LeagueClient" "--ux-name=LeagueClientUx" "--ux-helper-name=LeagueClientUxHelper" "--log-dir=LeagueClient Logs" "--crash-reporting=crashpad" "--crash-environment=LA2" "--crash-pipe=\\.\pipe\crashpad_10064_VYEQGUMUTQNMNCKV" "--app-log-file-path=C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2021-12-11T17-58-28_10064_LeagueClient.log" "--app-pid=10064" "--output-base-dir=C:\Riot Games\League of Legends" "--no-proxy-server"

**Comment by SharkiCS** [comment]
Gracias Axel, ya he visto el problema, es un problema con la región. En su momento no pude testear con todas las regiones y di por sentado que seguirian la misma nomenclatura que en Euw, sin embargo en Las no es Las, sino La2. En un ratillo lo fixeo y te aviso. 

Una ultima cosa, actualiza tu Key Api, la has publicado por aquí y cualquiera podría mandar requests desde tu cuenta a la api de riot. (Basta con que le des al botón que dice regenerate api key). Lo dicho, en un ratillo lo cambio y te aviso! :)

**Comment by Axel3026** [comment]
Muchisimas Graciass a vos, y que tengas un lindo dia, voy a estar atento a las proximas actualizaciones. <3. Esto capaz te ayude con otros servidores https://leagueoflegends.fandom.com/es/wiki/Servidores

**Comment by SharkiCS** [comment]
Fixed! Puedes rebuildear el proyecto o simplemente descargar el nuevo binario, me avisas si ahora te funciona correctamente para marcar como resuelto el issue.

![image](https://user-images.githubusercontent.com/33672039/145692415-7af2e760-49a7-4f95-8091-1f8483e5c374.png)

¡Y gracias por el enlace! desafortunadamente la libreria de RiotSharp no sigue la misma nomenclatura que la de la LCU, por ejemplo: 

Region Europea según la abreviacion de la wiki (EUW1) no concuerda con la de RiotSharp (Euw) y la de la LCU (Euw). 
Region Latinoamericana Sur según la abreviacion de la wiki (LAS2)  **SI** concuerda con la de RiotSharp (LAS) y la de la LCU (LA2). 

De todas formas cuando tenga un poquillo de tiempo le echaré un vistazo más detalladamente a este problema con las regiones que seguramente hay algunas más que aún no funcionen. 

¡Que tengas un buen día!

**Comment by Axel3026** [comment]
a que mal, pensé que la wiki iba a servir de algo, igual muchas gracias, ahora si funciona correctamente, muchisimas gracias por la ayuda. Que tengas un lindo día.

![image](https://user-images.githubusercontent.com/87623383/145692809-623af327-40d4-45be-a336-cdfca4976427.png)
